apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: jupiterlab
  name: jupiterlab
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
    nodePort: 30493
  type: NodePort
  selector:
    io.kompose.service: jupiterlab
status:
  loadBalancer: {}
